### ISSUE TITLE
Invalid argument error: lz4 IPC decompression requires the lz4 feature

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#929]
**Describe the bug**

I am trying to run queries with Ballista but I get this error on the client.

```
Fail: Arrow error: Invalid argument error: lz4 IPC decompression requires the lz4 feature
```

I am not yet sure where this is coming from.

I do not see any lz4 feature in the Ballista Cargo.toml files.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by andygrove** [comment]
@Dandandan Any suggestions on tracking this down?

**Comment by Dandandan** [comment]
Hm but this seems to be currently enabled, are you somehow running a version without `ipc_compression` set?

**Comment by andygrove** [comment]
I built Ballista from [this PR](https://github.com/apache/arrow-ballista/pull/927) with `cargo build --release`.

My client is at https://github.com/sql-benchmarks/sqlbench-runners/pull/32 and has these dependencies:

```toml
[dependencies]
ballista = { git = "https://github.com/andygrove/arrow-ballista", branch="df-34" }
datafusion = { git = "https://github.com/apache/arrow-datafusion", rev = "d091b55be6a4ce552023ef162b5d081136d3ff6d" }
```

It has been a long time since I worked on this project so maybe I am just missing something obvious.
